config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "home/index"
  root "home#index"

  get "synchronisation/index"
  patch "synchronisation/synchronise_action"

  get "analytics/index"
  patch "analytics/select_preseller_action"
  patch "analytics/select_contractor_action"

  resources :trading_agents, only: [:index, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client_debt_datum.rb
class ClientDebtDatum < ApplicationRecord
  belongs_to :week
  belongs_to :contractor, foreign_key: :contract_id
  scope :by_weeks_ascending, -> { joins(:week).order("weeks.monday ASC") }
end

app/models/contract.rb
class Contract < ApplicationRecord
  self.primary_key = "contract_id"
  belongs_to :subdivision
  belongs_to :trading_agent
  belongs_to :currency
  belongs_to :contractor, foreign_key: :customer_id

  # scope :sort_by_heighest_debt, -> { order(preseller: true) }
end

app/models/contractor.rb
class Contractor < ApplicationRecord
  self.primary_key = "customer_id"
  has_many :contracts, foreign_key: :customer_id
  has_many :client_debt_data, foreign_key: :contract_id

  scope :by_debt_descending, -> { order(debt: :desc) }
end

app/models/currency.rb
class Currency < ApplicationRecord
  self.primary_key = "currency_id"
  has_many :contracts
end

app/models/operation.rb
class Operation < ApplicationRecord
  default_scope { order(created_at: :asc) }

  include ActionView::Helpers::DateHelper
  def time_from_last_sync
    time_ago_in_words(updated_at)
  end
end

app/models/subdivision.rb
class Subdivision < ApplicationRecord
  self.primary_key = "subdivision_id"
  has_many :contracts
end

app/models/trading_agent.rb
class TradingAgent < ApplicationRecord
  self.primary_key = "trading_agent_id"
  has_many :contracts
  has_many :contractors, through: :contracts
  scope :preseller, -> { where(preseller: true) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are: :registerable
  # :confirmable, :lockable,  :recoverable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/models/week.rb
class Week < ApplicationRecord
  has_many :client_debt_data

  scope :for_year, lambda { |year|
    where(
      '"monday" >= ? AND monday < ?',
      Date.commercial(year, 1, 1),
      Date.commercial(year + 1, 1, 1)
    )
  }

  scope :sort_ascending, -> { order(monday: :asc) }
  scope :sort_descending, -> { order(monday: :desc) }
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  before_action :set_preseller, only: [:select_preseller_action]
  before_action :set_contractor, only: [:select_contractor_action]
  respond_to :json, only: [:select_preseller_action, :select_contractor_action]

  def index
    @presellers = TradingAgent.preseller
  end

  def select_preseller_action
    return if @preseller.nil?
    @preseller_contractors = "<option value='' disabled selected>#{I18n.t(:select_contractor)}</option>"

    @preseller.contractors.by_debt_descending.each do |contractor|
      next if contractor.nil?
      @preseller_contractors +=
        "<option value='#{contractor.customer_id}'>#{contractor.customer_name} - #{(contractor.debt / 1000).round(1)}k</option>"
    end
  end

  def select_contractor_action
    return if @contractor.nil?

    @client_debt_data = ""
    weeks = Week.for_year(analytics_params[:year].to_i).sort_descending
    weeks.each.with_index(0).map do |week, index|
      # option 2
      # client_debt_datum = week.client_debt_data.where(contract_id: @contractor.customer_id)
      client_debt_datum = @contractor.client_debt_data.where(week_id: week.id).first
      next if client_debt_datum.nil?
      week_number = (weeks.length - index).to_s.rjust(2, "0")
      date = week.monday.strftime("%d / %B / %Y")

      @client_debt_data +=
        render_to_string partial: "analytics/week", locals: {
          week_number: week_number,
          date: date,
          client_debt_datum: client_debt_datum
        }
    end
  end

  private

    def set_preseller
      @preseller = TradingAgent.where(trading_agent_id: analytics_params[:preseller_id]).first
    end

    def set_contractor
      @contractor = Contractor.where(customer_id: analytics_params[:contractor_id]).first
    end

    def analytics_params
      params.require(:analytics).permit(:preseller_id, :contractor_id, :year)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  YEAR_SETTER = 2017
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contractors_by_debt = Contractor.by_debt_descending.first(50).reverse
    respond_to do |format|
      format.html { render home_index_path }
      format.json { render home_index_path }
    end
  end
end

app/controllers/synchronisation_controller.rb
class SynchronisationController < ApplicationController
  respond_to :json, only: [:synchronise_action]
  include SavonLib
  include ActionView::Helpers::DateHelper

  def index
    # initialize operations table
    get_operations(initialize_savon) if Operation.all.empty?
    @operations = Operation.all
    @mondays_array = initialize_mondays_array
  end

  def synchronise_action
    start = Time.zone.now # Start time elapse

    savon_response = nil
    operation_code = synchronisation_params[:operation_code].to_i

    savon_response = get_operation(operation_code) if (0..4).cover?(operation_code)

    if !savon_response.nil? && savon_response.http.code == 200
      update_operation_updated_at(operation_code)

      @type = "success"
      @message = t(:synchronisation_is_successful)

      if (0..4).cover?(operation_code)
        helper_sync(operation_code, savon_response.body)
      end
    elsif operation_code == 5
      resp = helper_sync(operation_code, nil, synchronisation_params[:week_date].to_date)
      @type = resp[0]
      update_operation_updated_at(operation_code) if @type == "success"
      @message = resp[1]
    else
      @type = "error"
      @message = t(:sync_failed)
    end

    @time_elapsed = "#{t(:operation_finished_in)} #{time_ago_in_words(start, include_seconds: true)}."
  end

  private

    # 0 :get_subdivision
    # 1 :get_trading_agents
    # 2 :get_currencies
    # 3 :get_contractors
    # 4 :get_contracts
    # 5 :get_client_debt_data_view_model

    def initialize_mondays_array
      date_index = Date.commercial(YEAR_SETTER, 1, 1)
      arr = []
      until date_index >= Time.zone.now.beginning_of_week
        arr << ["#{date_index.cweek.to_s.rjust(2, '0')} | #{date_index.strftime('%B %d, %Y')}", date_index]
        date_index = date_index.next_week
      end

      arr.reverse
    end

    def update_operation_updated_at(operation_code)
      Operation.find_by(
        operation_code: operation_code
      ).update_attributes(updated_at: Time.zone.now)
    end

    # Update operations table ONLY if empty
    def get_operations(initialize_savon)
      helper_refresh_operations_table(initialize_savon)
    end

    def get_operation(operation_code)
      helper_get_response_body(initialize_savon, operation_code)
    end

    def synchronisation_params
      params.require(:synchronisation).permit(:operation_code, :week_date)
    end
end

app/controllers/trading_agents_controller.rb
class TradingAgentsController < ApplicationController
  before_action :set_trading_agent, only: [:edit, :update]

  def index
    @trading_agents = TradingAgent.all.order(preseller: :asc)
  end

  def edit
  end

  def update
    if @trading_agent.update(trading_agent_params)
      redirect_to trading_agents_path, notice: "Trading agent was successfully updated."
    else
      render :edit
    end
  end

  private

    def set_trading_agent
      @trading_agent = TradingAgent.find(params[:id])
    end

    def trading_agent_params
      params.require(:trading_agent).permit(:trading_agent_id, :preseller)
    end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    "active" if current_page?(link_path)
  end

  def alertifyjs_flash
    flash_messages = []
    flash.each do |type, message|
      type = "success" if type == "notice"
      type = "warning" if type == "warning"
      type = "error"   if type == "alert"
      text = "<script>alertify.#{type}('#{message}'); </script>"
      flash_messages << text.html_safe if message
    end

    flash_messages.join("\n").html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/synchronisation_helper.rb
module SynchronisationHelper
end

app/helpers/trading_agents_helper.rb
module TradingAgentsHelper
end

app/views/analytics/_analytics_info_wrapper_data.html.haml
.col-wrapper.col-sm-3
  .col-wrapper-inner
    %h5
      =t(:contract_info)

    %dl.row
      %dt.col-sm-5
        ="#{t(:name)}:"
      %dd.col-sm-7.contract-name

      %dt.col-sm-5
        ="#{t(:type)}:"
      %dd.col-sm-7.contract-type

      %dt.col-sm-5
        ="#{t(:currency)}:"
      %dd.col-sm-7.contract-currency

      %dt.col-sm-5
        ="#{t(:preseller)}:"
      %dd.col-sm-7.contract-preseller

      %dt.col-sm-5
        ="#{t(:subdivision)}:"
      %dd.col-sm-7.contract-subdivision

.col-wrapper.col-sm-5
  .col-wrapper-inner
    %h5
      =t(:contractor_info)

    %dl.row
      %dt.col-sm-4
        ="#{t(:name)}:"
      %dd.col-sm-8.contractor-name

      %dt.col-sm-4
        ="#{t(:code)}:"
      %dd.col-sm-8.contractor-code

      %dt.col-sm-4
        ="#{t(:state_id)}:"
      %dd.col-sm-8.contractor-state-id

      %dt.col-sm-4
        ="#{t(:physical_address)}:"
      %dd.col-sm-8.contractor-physical-address

      %dt.col-sm-4
        ="#{t(:legal_address)}:"
      %dd.col-sm-8.contractor-legal-address

      %dt.col-sm-4
        ="#{t(:type)}:"
      %dd.col-sm-8.contractor-type

app/views/analytics/_week.html.haml
.week-header
  %h5
    %span.week-number=week_number
    =date
.week-body
  %dl.row
    -if (client_debt_datum.amount_beginning - client_debt_datum.amount_the_end) != 0 || client_debt_datum.sales != 0 || client_debt_datum.payment != 0
      %dt.col-sm-2=t(:amount_beggining)
      %dd.col-sm-10
        %span.amount-beginning
          = client_debt_datum.amount_beginning unless client_debt_datum.nil?

    -if client_debt_datum.sales != 0
      %dt.col-sm-2=t(:sales)
      %dd.col-sm-10
        %span.sales
          = client_debt_datum.sales unless client_debt_datum.nil?

    -if client_debt_datum.sales_returns != 0
      %dt.col-sm-2=t(:sales_returns)
      %dd.col-sm-10
        %span.sales-returns
          = client_debt_datum.sales_returns unless client_debt_datum.nil?

    -if client_debt_datum.debt_adjustment != 0
      %dt.col-sm-2=t(:debt_adjustment)
      %dd.col-sm-10
        %span.debt-adjustment
          = client_debt_datum.debt_adjustment unless client_debt_datum.nil?

    -if client_debt_datum.payment != 0
      %dt.col-sm-2=t(:payment)
      %dd.col-sm-10
        %span.payment
          = client_debt_datum.payment unless client_debt_datum.nil?

    -if client_debt_datum.amount_returns != 0
      %dt.col-sm-2=t(:amount_returns)
      %dd.col-sm-10
        %span.amount-returns
          = client_debt_datum.amount_returns unless client_debt_datum.nil?

    -if client_debt_datum.amount_the_end != 0
      %dt.col-sm-2=t(:amount_the_end)
      %dd.col-sm-10
        %span.amount-the-end
          = client_debt_datum.amount_the_end unless client_debt_datum.nil?

app/views/analytics/index.html.haml
%h1=t(:analytics)
%br
.analytics-header-wrapper.container-fluid
  .row
    .col-wrapper.col-sm-4
      .col-wrapper-inner
        =t(:select_year)
        %br
        =select_year Date.today, { start_year: 2014, end_year: Date.today.year }, { class: "custom-select" }
        %br
        %br
        =t(:presellers)
        %br
        =collection_select(:preseller, :id, @presellers, :id, :trading_agent_name, {prompt: true}, {class: "custom-select", autocomplete: "off"})
        %br
        %br
        =t(:contractors)
        =select_tag :contractor_id, nil, { prompt: "--#{t(:select_preseller_first)}--", id: "contractor-selector", class: "", autocomplete: "off", style: "width: 100%;"}
    = render "analytics_info_wrapper_data"

%br

.analytics-body-wrapper

app/views/home/index.html.haml
%h1=t(:welcome_to_smugglers_kitchen)
%br
#contractors_by_debt

:javascript
  init_canvasjs();

app/views/layouts/_header.html.haml
%nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
  %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarText", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarText", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  =link_to t(:smugglers_kitchen), root_path, class: "navbar-brand"
  #navbarText.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item
        =link_to t(:analytics), analytics_index_path, class: "nav-link #{active_class(analytics_index_path)}"
      %li.nav-item
        =link_to t(:synchronisation), synchronisation_index_path, class: "nav-link #{active_class(synchronisation_index_path)}"
      %li.nav-item
        =link_to t(:trading_agents), trading_agents_path, class: "nav-link #{active_class(trading_agents_path)}"
    .dropdown
      %button#dropdownMenuButton.btn.btn-secondary.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
        -if current_user
          =current_user.email
        - else
          Login
      .dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
        -if current_user
          =link_to "Logout", destroy_user_session_path, class: "dropdown-item", method: :delete
        - else
          =link_to "Login", new_user_session_path, class: "dropdown-item"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv": "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title SmugglersKitchen
    = csrf_meta_tags
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
  %body
    = alertifyjs_flash
    = render "layouts/header"
    .wrapper
      = yield

app/views/synchronisation/index.html.haml
%br
%h1 Synchronisations
%br

%table.table.table-bordered.table-hover
  %thead.thead-default
    %tr
      %th #
      %th Operation Name
      %th Last Synced
      %th
  %tbody
    - @operations.each.with_index(1) do |operation, index|
      %tr
        %td= index
        %td= operation.operation_name
        %td= operation.time_from_last_sync
        %td
          -if index == 6
            -# = select_date Date.today, { prefix: :date, with_css_classes: true}, { class: "custom-select" }
            = select_tag :week_date, options_for_select(@mondays_array), class: "custom-select date"
            %br
            %br

          %button{ class: "synchronise-action btn btn-info",
                   operation_code: operation.operation_code }
            Synchronise

app/views/trading_agents/_form.html.haml
= form_for @trading_agent do |f|
  - if @trading_agent.errors.any?
    #error_explanation
      %h2= "#{pluralize(@trading_agent.errors.count, "error")} prohibited this trading_agent from being saved:"
      %ul
        - @trading_agent.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.label :trading_agent_code
    = f.text_field :trading_agent_code, readonly: true
  .form-group
    = f.label :trading_agent_name
    = f.text_field :trading_agent_name, readonly: true
  .form-check
    %label.form-check-label
      = f.check_box :preseller, class: "form-check-input"
      = t(:preseller)
  .actions
    = f.submit "Save", class: "btn btn-default"

app/views/trading_agents/edit.html.haml
%h1=t(:editing_trading_agent)

= render "form"

%br
= link_to "Back", trading_agents_path, class: "btn btn-primary"

app/views/trading_agents/index.html.haml
%h1=t(:trading_agents)

%table.table.table-bordered.table-hover
  %thead
    %tr
      %th.col-sm-5 Trading agent code
      %th.col-sm-5 Trading agent name
      %th.col-sm-1 Preseller
      %th.col-sm-1

  %tbody
    - @trading_agents.each do |trading_agent|
      %tr
        %td= trading_agent.trading_agent_code
        %td= trading_agent.trading_agent_name
        %td= trading_agent.preseller
        %td= link_to "Edit", edit_trading_agent_path(trading_agent), class: "btn btn-warning"

%br